server.port=${PORT:8085}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/camunda_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:likhitha@0805}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ActiveMQ
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}

# Camunda
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.admin-user.firstName=Admin

# Downstream services Integration URLs
service.delivery.url=${DELIVERY_SERVICE_URL:http://localhost:8084}
service.kitchen.url=${KITCHEN_SERVICE_URL:http://localhost:8083}
service.order.url=${ORDER_SERVICE_URL:http://localhost:8081}
service.payment.url=${PAYMENT_SERVICE_URL:http://localhost:8086}
